######################################################################
# Automatically generated by qmake (3.1) Tue Jul 7 16:14:34 2020
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += \
    tst_utilities \
    tst_dbmanager
